name: philand-ci

on:
  push:
    branches: [ "main","sandbox" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Meta
        id: meta
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login Harbor
        run: |
          printf '%s' '${{ secrets.HARBOR_PASS }}' | \
          docker login ${{ secrets.HARBOR_HOST }} -u '${{ secrets.HARBOR_USER }}' --password-stdin

      - name: Build & Push API
        run: |
          IMG="${{ secrets.HARBOR_HOST }}/philand/api:${{ steps.meta.outputs.TAG }}"
          docker build -t "$IMG" -f Dockerfile .
          docker push "$IMG"

      - name: Build & Push WEB
        run: |
          IMG="${{ secrets.HARBOR_HOST }}/philand/web:${{ steps.meta.outputs.TAG }}"
          docker build -t "$IMG" \
            --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" \
            --build-arg NEXT_PUBLIC_API_URL="${{ vars.NEXT_PUBLIC_API_URL }}" \
            --build-arg NEXT_PUBLIC_APP_NAME="Philand" \
            --build-arg NEXT_PUBLIC_APP_VERSION="${{ github.sha }}" \
            -f web/Dockerfile web
          docker push "$IMG"

      - name: Update kustomize tag
        run: |
          TAG=${GITHUB_SHA::7}
          sed -i "s/newTag: \".*\"/newTag: \"${TAG}\"/g" deploy/overlays/dev/kustomization.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deploy/overlays/dev/kustomization.yaml
          git commit -m "chore: bump image tag ${TAG}" || exit 0
          git push
